sudo: required

language: python

python:
- "3.6"

branches:
  only:
    - master

before_install:
    - sudo apt-get install python-pip
    - pip install -r requirements.txt
    - sudo apt-get update
    - wget --no-check-certificate https://github.com/ideawu/ssdb/archive/master.zip
    - unzip master
    - cd ssdb-master
    - make
    - sudo make install
    - cd ../
    - sudo /usr/local/ssdb/ssdb-server -d /usr/local/ssdb/ssdb.conf

install:
    - pip install -e .[tests]

script:
    - pytest